name: Test Action

on:
  push:
    branches: [main]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      contents: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable

      - name: Pre-install stellarpath-cli
        run: cargo install --git https://github.com/STELLAR-PATH/stellarpath-cli.git --branch main

      - name: Create mock directory
        run: |
          mkdir -p mock-project
          echo "mock" > mock-project/test.txt

      - name: Run stellarpath-action
        uses: ./
        with:
          path: './mock-project'
          format: 'markdown'
          post-comment: 'false'
          github-token: ${{ secrets.GITHUB_TOKEN }}
